#pragma once

#define PE_FILE_MAXCHAR_ERROR 256

#define PE_FILE_NO_ERRORS 0x00000000
#define PE_FILE_NOT_INITIALIZED 0xFFFFFFFF
#define PE_FILE_INVALID_DOS_HEADER 0xA0000000
#define PE_FILE_INVALID_PE_HEADER 0xB0000000
#define PE_FILE_BAD_READ 0xC0000000
#define PE_FILE_BAD_WRITE 0xD0000000
#define PE_FILE_NOT_OPEN 0xE0000000

typedef unsigned int PE_FILE_EXCPT;
DWORD PE_FILE_Exception(DWORD dwExceptionCodeReceived, 
	LPEXCEPTION_POINTERS lpExceptionInfo, LPTSTR szBuffer, PE_FILE* file);

void PE_FILE_WriteLog(LPCTSTR str);
