/********************************************************************************
** Form generated from reading UI file 'QtGuiPE.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_QTGUIPE_H
#define UI_QTGUIPE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDateTimeEdit>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_QtGuiPEClass
{
public:
    QWidget *centralWidget;
    QFrame *frame;
    QFrame *frame_2;
    QLabel *msdos_label;
    QLineEdit *e_lfanew;
    QLineEdit *e_crlc;
    QLabel *label_5;
    QLineEdit *e_lfarlc;
    QLineEdit *e_csum;
    QLineEdit *e_oemid;
    QLabel *label_6;
    QLineEdit *e_maxalloc;
    QLabel *label_8;
    QLineEdit *e_minalloc;
    QLineEdit *e_cparhdr;
    QLabel *label_3;
    QLineEdit *e_cp;
    QLineEdit *e_magic;
    QLineEdit *e_cs;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_17;
    QLineEdit *e_cblp;
    QLabel *label_11;
    QLabel *label;
    QLabel *label_10;
    QLabel *label_4;
    QLineEdit *e_ss;
    QLineEdit *e_oeminfo;
    QLabel *label_18;
    QLabel *label_13;
    QLineEdit *e_ovno;
    QLabel *label_16;
    QLabel *label_12;
    QLineEdit *e_ip;
    QLabel *label_7;
    QLineEdit *e_sp;
    QLabel *label_2;
    QPushButton *OpenFilePushButton;
    QFrame *frame_3;
    QLabel *fileheader_label;
    QLabel *label_21;
    QLabel *label_19;
    QLineEdit *Machine;
    QLineEdit *Machine_Word;
    QLabel *label_20;
    QLineEdit *NumberOfSections;
    QLineEdit *TimeDateStamp;
    QLabel *label_22;
    QLineEdit *PointerToSymbolTable;
    QLabel *label_23;
    QLineEdit *NumberOfSymbols;
    QLabel *label_24;
    QLineEdit *SizeOfOptionalHeader;
    QLabel *label_25;
    QLineEdit *Characteristics;
    QPushButton *CharacteristicsPushButton;
    QDateTimeEdit *TimeDateStamp_dateTimeEdit;
    QFrame *frame_4;
    QLabel *label_9;
    QLabel *label_26;
    QLineEdit *MagicOp;
    QLabel *label_27;
    QLineEdit *MajorLinkerVersion;
    QLabel *label_28;
    QLineEdit *MinorLinkerVersion;
    QLabel *label_29;
    QLineEdit *SizeOfCode;
    QLabel *label_30;
    QLineEdit *SizeOfInitializedData;
    QLabel *label_31;
    QLineEdit *SizeOfUninitializedData;
    QLabel *label_32;
    QLineEdit *AddressOfEntryPoint;
    QLabel *label_33;
    QLineEdit *BaseOfCode;
    QLabel *label_34;
    QLineEdit *BaseOfData;
    QLabel *label_35;
    QLineEdit *ImageBase;
    QLabel *label_36;
    QLineEdit *SectionAlignment;
    QLabel *label_37;
    QLineEdit *FileAlignment;
    QLineEdit *MinorSubsystemVersion;
    QLabel *label_42;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLineEdit *MajorSubsystemVersion;
    QLabel *label_43;
    QLineEdit *MinorImageVersion;
    QLineEdit *MajorImageVersion;
    QLineEdit *MajorOperatingSystemVersion;
    QLineEdit *MinorOperatingSystemVersion;
    QLabel *label_38;
    QLabel *label_44;
    QLineEdit *Win32VersionValue;
    QLabel *label_45;
    QLineEdit *SizeOfImage;
    QLabel *label_46;
    QLineEdit *SizeOfHeaders;
    QLabel *label_47;
    QLineEdit *CheckSum;
    QLabel *label_50;
    QLineEdit *SizeOfStackReserve;
    QLabel *label_51;
    QLineEdit *SizeOfStackCommit;
    QLabel *label_52;
    QLineEdit *SizeOfHeapReserve;
    QLabel *label_55;
    QLineEdit *NumberOfRvaAndSizes;
    QLabel *label_53;
    QLineEdit *SizeOfHeapCommit;
    QLabel *label_54;
    QLineEdit *LoaderFlags;
    QLabel *label_48;
    QLineEdit *Subsystem;
    QLineEdit *Subsystem_Word;
    QLabel *label_49;
    QLineEdit *DllCharacteristics;
    QPushButton *DLLCharacteristicsPushButton;
    QPushButton *DataDirectoryPushButton;
    QPushButton *SectionsPushButton;
    QPushButton *ClosePushButton;

    void setupUi(QMainWindow *QtGuiPEClass)
    {
        if (QtGuiPEClass->objectName().isEmpty())
            QtGuiPEClass->setObjectName(QStringLiteral("QtGuiPEClass"));
        QtGuiPEClass->setEnabled(true);
        QtGuiPEClass->resize(710, 530);
        QSizePolicy sizePolicy(QSizePolicy::Maximum, QSizePolicy::Maximum);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(QtGuiPEClass->sizePolicy().hasHeightForWidth());
        QtGuiPEClass->setSizePolicy(sizePolicy);
        QtGuiPEClass->setContextMenuPolicy(Qt::NoContextMenu);
        QtGuiPEClass->setToolButtonStyle(Qt::ToolButtonIconOnly);
        QtGuiPEClass->setTabShape(QTabWidget::Rounded);
        centralWidget = new QWidget(QtGuiPEClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(10, 10, 691, 511));
        frame->setFrameShape(QFrame::WinPanel);
        frame->setFrameShadow(QFrame::Raised);
        frame->setLineWidth(2);
        frame->setMidLineWidth(0);
        frame_2 = new QFrame(frame);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(10, 10, 211, 371));
        frame_2->setFrameShape(QFrame::Box);
        frame_2->setFrameShadow(QFrame::Raised);
        msdos_label = new QLabel(frame_2);
        msdos_label->setObjectName(QStringLiteral("msdos_label"));
        msdos_label->setEnabled(true);
        msdos_label->setGeometry(QRect(10, 0, 201, 21));
        QFont font;
        font.setFamily(QStringLiteral("Lucida Console"));
        font.setPointSize(13);
        font.setUnderline(true);
        msdos_label->setFont(font);
        msdos_label->setFrameShadow(QFrame::Plain);
        msdos_label->setTextFormat(Qt::AutoText);
        e_lfanew = new QLineEdit(frame_2);
        e_lfanew->setObjectName(QStringLiteral("e_lfanew"));
        e_lfanew->setEnabled(true);
        e_lfanew->setGeometry(QRect(100, 340, 101, 20));
        QFont font1;
        font1.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font1.setPointSize(8);
        font1.setBold(false);
        font1.setWeight(50);
        e_lfanew->setFont(font1);
        e_lfanew->setFrame(true);
        e_lfanew->setReadOnly(true);
        e_lfanew->setClearButtonEnabled(false);
        e_crlc = new QLineEdit(frame_2);
        e_crlc->setObjectName(QStringLiteral("e_crlc"));
        e_crlc->setEnabled(true);
        e_crlc->setGeometry(QRect(150, 80, 51, 20));
        e_crlc->setFont(font1);
        e_crlc->setFrame(true);
        e_crlc->setReadOnly(true);
        e_crlc->setClearButtonEnabled(false);
        label_5 = new QLabel(frame_2);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setEnabled(true);
        label_5->setGeometry(QRect(10, 140, 77, 20));
        label_5->setFont(font1);
        label_5->setFrameShape(QFrame::NoFrame);
        label_5->setFrameShadow(QFrame::Plain);
        e_lfarlc = new QLineEdit(frame_2);
        e_lfarlc->setObjectName(QStringLiteral("e_lfarlc"));
        e_lfarlc->setEnabled(true);
        e_lfarlc->setGeometry(QRect(150, 260, 51, 20));
        e_lfarlc->setFont(font1);
        e_lfarlc->setFrame(true);
        e_lfarlc->setReadOnly(true);
        e_lfarlc->setClearButtonEnabled(false);
        e_csum = new QLineEdit(frame_2);
        e_csum->setObjectName(QStringLiteral("e_csum"));
        e_csum->setEnabled(true);
        e_csum->setGeometry(QRect(150, 200, 51, 20));
        e_csum->setFont(font1);
        e_csum->setFrame(true);
        e_csum->setReadOnly(true);
        e_csum->setClearButtonEnabled(false);
        e_oemid = new QLineEdit(frame_2);
        e_oemid->setObjectName(QStringLiteral("e_oemid"));
        e_oemid->setEnabled(true);
        e_oemid->setGeometry(QRect(150, 300, 51, 20));
        e_oemid->setFont(font1);
        e_oemid->setFrame(true);
        e_oemid->setReadOnly(true);
        e_oemid->setClearButtonEnabled(false);
        label_6 = new QLabel(frame_2);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setEnabled(true);
        label_6->setGeometry(QRect(10, 280, 77, 20));
        label_6->setFont(font1);
        label_6->setFrameShape(QFrame::NoFrame);
        label_6->setFrameShadow(QFrame::Plain);
        e_maxalloc = new QLineEdit(frame_2);
        e_maxalloc->setObjectName(QStringLiteral("e_maxalloc"));
        e_maxalloc->setEnabled(true);
        e_maxalloc->setGeometry(QRect(150, 140, 51, 20));
        e_maxalloc->setFont(font1);
        e_maxalloc->setFrame(true);
        e_maxalloc->setReadOnly(true);
        e_maxalloc->setClearButtonEnabled(false);
        label_8 = new QLabel(frame_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setEnabled(true);
        label_8->setGeometry(QRect(10, 180, 77, 20));
        label_8->setFont(font1);
        label_8->setFrameShape(QFrame::NoFrame);
        label_8->setFrameShadow(QFrame::Plain);
        e_minalloc = new QLineEdit(frame_2);
        e_minalloc->setObjectName(QStringLiteral("e_minalloc"));
        e_minalloc->setEnabled(true);
        e_minalloc->setGeometry(QRect(150, 120, 51, 20));
        e_minalloc->setFont(font1);
        e_minalloc->setFrame(true);
        e_minalloc->setReadOnly(true);
        e_minalloc->setClearButtonEnabled(false);
        e_cparhdr = new QLineEdit(frame_2);
        e_cparhdr->setObjectName(QStringLiteral("e_cparhdr"));
        e_cparhdr->setEnabled(true);
        e_cparhdr->setGeometry(QRect(150, 100, 51, 20));
        e_cparhdr->setFont(font1);
        e_cparhdr->setFrame(true);
        e_cparhdr->setReadOnly(true);
        e_cparhdr->setClearButtonEnabled(false);
        label_3 = new QLabel(frame_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setEnabled(true);
        label_3->setGeometry(QRect(10, 60, 77, 20));
        label_3->setFont(font1);
        label_3->setFrameShape(QFrame::NoFrame);
        label_3->setFrameShadow(QFrame::Plain);
        e_cp = new QLineEdit(frame_2);
        e_cp->setObjectName(QStringLiteral("e_cp"));
        e_cp->setEnabled(true);
        e_cp->setGeometry(QRect(150, 60, 51, 20));
        e_cp->setFont(font1);
        e_cp->setFrame(true);
        e_cp->setReadOnly(true);
        e_cp->setClearButtonEnabled(false);
        e_magic = new QLineEdit(frame_2);
        e_magic->setObjectName(QStringLiteral("e_magic"));
        e_magic->setEnabled(true);
        e_magic->setGeometry(QRect(150, 20, 51, 20));
        e_magic->setFont(font1);
        e_magic->setFrame(true);
        e_magic->setReadOnly(true);
        e_magic->setClearButtonEnabled(false);
        e_cs = new QLineEdit(frame_2);
        e_cs->setObjectName(QStringLiteral("e_cs"));
        e_cs->setEnabled(true);
        e_cs->setGeometry(QRect(150, 240, 51, 20));
        e_cs->setFont(font1);
        e_cs->setFrame(true);
        e_cs->setReadOnly(true);
        e_cs->setClearButtonEnabled(false);
        label_14 = new QLabel(frame_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setEnabled(true);
        label_14->setGeometry(QRect(10, 260, 77, 20));
        label_14->setFont(font1);
        label_14->setFrameShape(QFrame::NoFrame);
        label_14->setFrameShadow(QFrame::Plain);
        label_15 = new QLabel(frame_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setEnabled(true);
        label_15->setGeometry(QRect(10, 240, 77, 20));
        label_15->setFont(font1);
        label_15->setFrameShape(QFrame::NoFrame);
        label_15->setFrameShadow(QFrame::Plain);
        label_17 = new QLabel(frame_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setEnabled(true);
        label_17->setGeometry(QRect(10, 200, 77, 20));
        label_17->setFont(font1);
        label_17->setFrameShape(QFrame::NoFrame);
        label_17->setFrameShadow(QFrame::Plain);
        e_cblp = new QLineEdit(frame_2);
        e_cblp->setObjectName(QStringLiteral("e_cblp"));
        e_cblp->setEnabled(true);
        e_cblp->setGeometry(QRect(150, 40, 51, 20));
        e_cblp->setFont(font1);
        e_cblp->setFrame(true);
        e_cblp->setReadOnly(true);
        e_cblp->setClearButtonEnabled(false);
        label_11 = new QLabel(frame_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setEnabled(true);
        label_11->setGeometry(QRect(10, 300, 51, 20));
        label_11->setFont(font1);
        label_11->setFrameShape(QFrame::NoFrame);
        label_11->setFrameShadow(QFrame::Plain);
        label = new QLabel(frame_2);
        label->setObjectName(QStringLiteral("label"));
        label->setEnabled(true);
        label->setGeometry(QRect(10, 20, 94, 20));
        label->setFont(font1);
        label->setFrameShape(QFrame::NoFrame);
        label->setFrameShadow(QFrame::Plain);
        label_10 = new QLabel(frame_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setEnabled(true);
        label_10->setGeometry(QRect(10, 120, 77, 20));
        label_10->setFont(font1);
        label_10->setFrameShape(QFrame::NoFrame);
        label_10->setFrameShadow(QFrame::Plain);
        label_4 = new QLabel(frame_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setEnabled(true);
        label_4->setGeometry(QRect(10, 80, 77, 20));
        label_4->setFont(font1);
        label_4->setFrameShape(QFrame::NoFrame);
        label_4->setFrameShadow(QFrame::Plain);
        e_ss = new QLineEdit(frame_2);
        e_ss->setObjectName(QStringLiteral("e_ss"));
        e_ss->setEnabled(true);
        e_ss->setGeometry(QRect(150, 160, 51, 20));
        e_ss->setFont(font1);
        e_ss->setFrame(true);
        e_ss->setReadOnly(true);
        e_ss->setClearButtonEnabled(false);
        e_oeminfo = new QLineEdit(frame_2);
        e_oeminfo->setObjectName(QStringLiteral("e_oeminfo"));
        e_oeminfo->setEnabled(true);
        e_oeminfo->setGeometry(QRect(150, 320, 51, 20));
        e_oeminfo->setFont(font1);
        e_oeminfo->setFrame(true);
        e_oeminfo->setReadOnly(true);
        e_oeminfo->setClearButtonEnabled(false);
        label_18 = new QLabel(frame_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setEnabled(true);
        label_18->setGeometry(QRect(10, 340, 46, 20));
        QFont font2;
        font2.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font2.setPointSize(8);
        label_18->setFont(font2);
        label_13 = new QLabel(frame_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setEnabled(true);
        label_13->setGeometry(QRect(10, 100, 77, 20));
        label_13->setFont(font1);
        label_13->setFrameShape(QFrame::NoFrame);
        label_13->setFrameShadow(QFrame::Plain);
        e_ovno = new QLineEdit(frame_2);
        e_ovno->setObjectName(QStringLiteral("e_ovno"));
        e_ovno->setEnabled(true);
        e_ovno->setGeometry(QRect(150, 280, 51, 20));
        e_ovno->setFont(font1);
        e_ovno->setFrame(true);
        e_ovno->setReadOnly(true);
        e_ovno->setClearButtonEnabled(false);
        label_16 = new QLabel(frame_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setEnabled(true);
        label_16->setGeometry(QRect(10, 220, 77, 20));
        label_16->setFont(font1);
        label_16->setFrameShape(QFrame::NoFrame);
        label_16->setFrameShadow(QFrame::Plain);
        label_12 = new QLabel(frame_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setEnabled(true);
        label_12->setGeometry(QRect(10, 320, 46, 20));
        label_12->setFont(font1);
        label_12->setFrameShape(QFrame::NoFrame);
        label_12->setFrameShadow(QFrame::Plain);
        e_ip = new QLineEdit(frame_2);
        e_ip->setObjectName(QStringLiteral("e_ip"));
        e_ip->setEnabled(true);
        e_ip->setGeometry(QRect(150, 220, 51, 20));
        e_ip->setFont(font1);
        e_ip->setFrame(true);
        e_ip->setReadOnly(true);
        e_ip->setClearButtonEnabled(false);
        label_7 = new QLabel(frame_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setEnabled(true);
        label_7->setGeometry(QRect(10, 160, 77, 20));
        label_7->setFont(font1);
        label_7->setFrameShape(QFrame::NoFrame);
        label_7->setFrameShadow(QFrame::Plain);
        e_sp = new QLineEdit(frame_2);
        e_sp->setObjectName(QStringLiteral("e_sp"));
        e_sp->setEnabled(true);
        e_sp->setGeometry(QRect(150, 180, 51, 20));
        e_sp->setFont(font1);
        e_sp->setFrame(true);
        e_sp->setReadOnly(true);
        e_sp->setClearButtonEnabled(false);
        label_2 = new QLabel(frame_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setEnabled(true);
        label_2->setGeometry(QRect(10, 40, 94, 20));
        label_2->setFont(font1);
        label_2->setFrameShape(QFrame::NoFrame);
        label_2->setFrameShadow(QFrame::Plain);
        OpenFilePushButton = new QPushButton(frame);
        OpenFilePushButton->setObjectName(QStringLiteral("OpenFilePushButton"));
        OpenFilePushButton->setGeometry(QRect(10, 390, 211, 23));
        QFont font3;
        font3.setFamily(QStringLiteral("Lucida Console"));
        font3.setPointSize(11);
        OpenFilePushButton->setFont(font3);
        OpenFilePushButton->setAutoDefault(false);
        OpenFilePushButton->setFlat(false);
        frame_3 = new QFrame(frame);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(230, 10, 451, 111));
        frame_3->setFrameShape(QFrame::Box);
        frame_3->setFrameShadow(QFrame::Raised);
        fileheader_label = new QLabel(frame_3);
        fileheader_label->setObjectName(QStringLiteral("fileheader_label"));
        fileheader_label->setEnabled(true);
        fileheader_label->setGeometry(QRect(10, 0, 131, 21));
        fileheader_label->setFont(font);
        label_21 = new QLabel(frame_3);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setEnabled(true);
        label_21->setGeometry(QRect(10, 80, 81, 20));
        label_21->setFont(font2);
        label_19 = new QLabel(frame_3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setEnabled(true);
        label_19->setGeometry(QRect(10, 20, 93, 20));
        label_19->setFont(font2);
        Machine = new QLineEdit(frame_3);
        Machine->setObjectName(QStringLiteral("Machine"));
        Machine->setEnabled(true);
        Machine->setGeometry(QRect(110, 20, 51, 20));
        Machine->setFont(font1);
        Machine->setFrame(true);
        Machine->setReadOnly(true);
        Machine_Word = new QLineEdit(frame_3);
        Machine_Word->setObjectName(QStringLiteral("Machine_Word"));
        Machine_Word->setEnabled(true);
        Machine_Word->setGeometry(QRect(160, 20, 71, 20));
        Machine_Word->setFont(font1);
        Machine_Word->setFrame(true);
        Machine_Word->setReadOnly(true);
        label_20 = new QLabel(frame_3);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setEnabled(true);
        label_20->setGeometry(QRect(10, 40, 93, 20));
        label_20->setFont(font2);
        NumberOfSections = new QLineEdit(frame_3);
        NumberOfSections->setObjectName(QStringLiteral("NumberOfSections"));
        NumberOfSections->setEnabled(true);
        NumberOfSections->setGeometry(QRect(150, 40, 51, 20));
        NumberOfSections->setFont(font1);
        NumberOfSections->setFrame(true);
        NumberOfSections->setReadOnly(true);
        TimeDateStamp = new QLineEdit(frame_3);
        TimeDateStamp->setObjectName(QStringLiteral("TimeDateStamp"));
        TimeDateStamp->setEnabled(true);
        TimeDateStamp->setGeometry(QRect(110, 80, 71, 20));
        TimeDateStamp->setFont(font1);
        TimeDateStamp->setFrame(true);
        TimeDateStamp->setReadOnly(true);
        label_22 = new QLabel(frame_3);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setEnabled(true);
        label_22->setGeometry(QRect(270, 20, 64, 20));
        label_22->setFont(font2);
        PointerToSymbolTable = new QLineEdit(frame_3);
        PointerToSymbolTable->setObjectName(QStringLiteral("PointerToSymbolTable"));
        PointerToSymbolTable->setEnabled(true);
        PointerToSymbolTable->setGeometry(QRect(340, 20, 101, 20));
        PointerToSymbolTable->setFont(font1);
        PointerToSymbolTable->setFrame(true);
        PointerToSymbolTable->setReadOnly(true);
        label_23 = new QLabel(frame_3);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setEnabled(true);
        label_23->setGeometry(QRect(270, 40, 49, 20));
        label_23->setFont(font2);
        NumberOfSymbols = new QLineEdit(frame_3);
        NumberOfSymbols->setObjectName(QStringLiteral("NumberOfSymbols"));
        NumberOfSymbols->setEnabled(true);
        NumberOfSymbols->setGeometry(QRect(340, 40, 101, 20));
        NumberOfSymbols->setFont(font1);
        NumberOfSymbols->setFrame(true);
        NumberOfSymbols->setReadOnly(true);
        label_24 = new QLabel(frame_3);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setEnabled(true);
        label_24->setGeometry(QRect(10, 60, 112, 20));
        label_24->setFont(font2);
        SizeOfOptionalHeader = new QLineEdit(frame_3);
        SizeOfOptionalHeader->setObjectName(QStringLiteral("SizeOfOptionalHeader"));
        SizeOfOptionalHeader->setEnabled(true);
        SizeOfOptionalHeader->setGeometry(QRect(150, 60, 51, 20));
        SizeOfOptionalHeader->setFont(font2);
        SizeOfOptionalHeader->setFrame(true);
        SizeOfOptionalHeader->setReadOnly(true);
        label_25 = new QLabel(frame_3);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setEnabled(true);
        label_25->setGeometry(QRect(270, 60, 71, 20));
        label_25->setFont(font2);
        Characteristics = new QLineEdit(frame_3);
        Characteristics->setObjectName(QStringLiteral("Characteristics"));
        Characteristics->setEnabled(true);
        Characteristics->setGeometry(QRect(390, 60, 51, 20));
        Characteristics->setFont(font2);
        Characteristics->setFrame(true);
        Characteristics->setReadOnly(true);
        CharacteristicsPushButton = new QPushButton(frame_3);
        CharacteristicsPushButton->setObjectName(QStringLiteral("CharacteristicsPushButton"));
        CharacteristicsPushButton->setGeometry(QRect(360, 60, 21, 21));
        TimeDateStamp_dateTimeEdit = new QDateTimeEdit(frame_3);
        TimeDateStamp_dateTimeEdit->setObjectName(QStringLiteral("TimeDateStamp_dateTimeEdit"));
        TimeDateStamp_dateTimeEdit->setGeometry(QRect(180, 80, 131, 20));
        TimeDateStamp_dateTimeEdit->setReadOnly(true);
        TimeDateStamp_dateTimeEdit->setCurrentSection(QDateTimeEdit::DaySection);
        TimeDateStamp_dateTimeEdit->setCalendarPopup(false);
        TimeDateStamp_dateTimeEdit->setTimeSpec(Qt::LocalTime);
        frame_4 = new QFrame(frame);
        frame_4->setObjectName(QStringLiteral("frame_4"));
        frame_4->setGeometry(QRect(230, 140, 451, 351));
        frame_4->setFrameShape(QFrame::Box);
        frame_4->setFrameShadow(QFrame::Raised);
        label_9 = new QLabel(frame_4);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 0, 171, 20));
        label_9->setFont(font);
        label_26 = new QLabel(frame_4);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(10, 20, 61, 20));
        QFont font4;
        font4.setPointSize(8);
        label_26->setFont(font4);
        MagicOp = new QLineEdit(frame_4);
        MagicOp->setObjectName(QStringLiteral("MagicOp"));
        MagicOp->setGeometry(QRect(150, 20, 51, 20));
        MagicOp->setReadOnly(true);
        label_27 = new QLabel(frame_4);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(10, 40, 111, 21));
        label_27->setFont(font4);
        MajorLinkerVersion = new QLineEdit(frame_4);
        MajorLinkerVersion->setObjectName(QStringLiteral("MajorLinkerVersion"));
        MajorLinkerVersion->setGeometry(QRect(170, 40, 31, 20));
        MajorLinkerVersion->setReadOnly(true);
        label_28 = new QLabel(frame_4);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(10, 60, 101, 21));
        label_28->setFont(font4);
        MinorLinkerVersion = new QLineEdit(frame_4);
        MinorLinkerVersion->setObjectName(QStringLiteral("MinorLinkerVersion"));
        MinorLinkerVersion->setGeometry(QRect(170, 60, 31, 20));
        MinorLinkerVersion->setReadOnly(true);
        label_29 = new QLabel(frame_4);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(10, 80, 60, 20));
        label_29->setFont(font4);
        SizeOfCode = new QLineEdit(frame_4);
        SizeOfCode->setObjectName(QStringLiteral("SizeOfCode"));
        SizeOfCode->setGeometry(QRect(100, 80, 101, 20));
        SizeOfCode->setReadOnly(true);
        label_30 = new QLabel(frame_4);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(10, 100, 77, 20));
        label_30->setFont(font4);
        SizeOfInitializedData = new QLineEdit(frame_4);
        SizeOfInitializedData->setObjectName(QStringLiteral("SizeOfInitializedData"));
        SizeOfInitializedData->setGeometry(QRect(100, 100, 101, 20));
        SizeOfInitializedData->setReadOnly(true);
        label_31 = new QLabel(frame_4);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(10, 120, 90, 20));
        label_31->setFont(font4);
        SizeOfUninitializedData = new QLineEdit(frame_4);
        SizeOfUninitializedData->setObjectName(QStringLiteral("SizeOfUninitializedData"));
        SizeOfUninitializedData->setGeometry(QRect(100, 120, 101, 20));
        SizeOfUninitializedData->setReadOnly(true);
        label_32 = new QLabel(frame_4);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(10, 140, 53, 20));
        label_32->setFont(font4);
        AddressOfEntryPoint = new QLineEdit(frame_4);
        AddressOfEntryPoint->setObjectName(QStringLiteral("AddressOfEntryPoint"));
        AddressOfEntryPoint->setGeometry(QRect(100, 140, 101, 20));
        AddressOfEntryPoint->setReadOnly(true);
        label_33 = new QLabel(frame_4);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 160, 64, 20));
        label_33->setFont(font4);
        BaseOfCode = new QLineEdit(frame_4);
        BaseOfCode->setObjectName(QStringLiteral("BaseOfCode"));
        BaseOfCode->setGeometry(QRect(100, 160, 101, 20));
        BaseOfCode->setReadOnly(true);
        label_34 = new QLabel(frame_4);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 180, 62, 20));
        BaseOfData = new QLineEdit(frame_4);
        BaseOfData->setObjectName(QStringLiteral("BaseOfData"));
        BaseOfData->setGeometry(QRect(100, 180, 101, 20));
        BaseOfData->setReadOnly(true);
        label_35 = new QLabel(frame_4);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 200, 56, 20));
        ImageBase = new QLineEdit(frame_4);
        ImageBase->setObjectName(QStringLiteral("ImageBase"));
        ImageBase->setGeometry(QRect(100, 200, 101, 20));
        ImageBase->setReadOnly(true);
        label_36 = new QLabel(frame_4);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 220, 85, 20));
        SectionAlignment = new QLineEdit(frame_4);
        SectionAlignment->setObjectName(QStringLiteral("SectionAlignment"));
        SectionAlignment->setGeometry(QRect(100, 220, 101, 20));
        SectionAlignment->setReadOnly(true);
        label_37 = new QLabel(frame_4);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 240, 66, 20));
        FileAlignment = new QLineEdit(frame_4);
        FileAlignment->setObjectName(QStringLiteral("FileAlignment"));
        FileAlignment->setGeometry(QRect(100, 240, 101, 20));
        FileAlignment->setReadOnly(true);
        MinorSubsystemVersion = new QLineEdit(frame_4);
        MinorSubsystemVersion->setObjectName(QStringLiteral("MinorSubsystemVersion"));
        MinorSubsystemVersion->setGeometry(QRect(390, 120, 51, 20));
        MinorSubsystemVersion->setReadOnly(true);
        label_42 = new QLabel(frame_4);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(210, 100, 120, 20));
        label_39 = new QLabel(frame_4);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(210, 40, 81, 20));
        label_40 = new QLabel(frame_4);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(210, 60, 98, 20));
        label_41 = new QLabel(frame_4);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(210, 80, 97, 20));
        MajorSubsystemVersion = new QLineEdit(frame_4);
        MajorSubsystemVersion->setObjectName(QStringLiteral("MajorSubsystemVersion"));
        MajorSubsystemVersion->setGeometry(QRect(390, 100, 51, 20));
        MajorSubsystemVersion->setReadOnly(true);
        label_43 = new QLabel(frame_4);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(210, 120, 119, 20));
        MinorImageVersion = new QLineEdit(frame_4);
        MinorImageVersion->setObjectName(QStringLiteral("MinorImageVersion"));
        MinorImageVersion->setGeometry(QRect(390, 80, 51, 20));
        MinorImageVersion->setReadOnly(true);
        MajorImageVersion = new QLineEdit(frame_4);
        MajorImageVersion->setObjectName(QStringLiteral("MajorImageVersion"));
        MajorImageVersion->setGeometry(QRect(390, 60, 51, 20));
        MajorImageVersion->setReadOnly(true);
        MajorOperatingSystemVersion = new QLineEdit(frame_4);
        MajorOperatingSystemVersion->setObjectName(QStringLiteral("MajorOperatingSystemVersion"));
        MajorOperatingSystemVersion->setGeometry(QRect(390, 20, 51, 20));
        MajorOperatingSystemVersion->setReadOnly(true);
        MinorOperatingSystemVersion = new QLineEdit(frame_4);
        MinorOperatingSystemVersion->setObjectName(QStringLiteral("MinorOperatingSystemVersion"));
        MinorOperatingSystemVersion->setGeometry(QRect(390, 40, 51, 20));
        MinorOperatingSystemVersion->setReadOnly(true);
        label_38 = new QLabel(frame_4);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(210, 20, 82, 20));
        label_44 = new QLabel(frame_4);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(210, 140, 68, 20));
        Win32VersionValue = new QLineEdit(frame_4);
        Win32VersionValue->setObjectName(QStringLiteral("Win32VersionValue"));
        Win32VersionValue->setGeometry(QRect(340, 140, 101, 20));
        Win32VersionValue->setReadOnly(true);
        label_45 = new QLabel(frame_4);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(210, 160, 65, 20));
        SizeOfImage = new QLineEdit(frame_4);
        SizeOfImage->setObjectName(QStringLiteral("SizeOfImage"));
        SizeOfImage->setGeometry(QRect(340, 160, 101, 20));
        SizeOfImage->setReadOnly(true);
        label_46 = new QLabel(frame_4);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(210, 180, 75, 20));
        SizeOfHeaders = new QLineEdit(frame_4);
        SizeOfHeaders->setObjectName(QStringLiteral("SizeOfHeaders"));
        SizeOfHeaders->setGeometry(QRect(340, 180, 101, 20));
        SizeOfHeaders->setReadOnly(true);
        label_47 = new QLabel(frame_4);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(210, 200, 48, 20));
        CheckSum = new QLineEdit(frame_4);
        CheckSum->setObjectName(QStringLiteral("CheckSum"));
        CheckSum->setGeometry(QRect(340, 200, 101, 20));
        CheckSum->setReadOnly(true);
        label_50 = new QLabel(frame_4);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(210, 220, 104, 20));
        SizeOfStackReserve = new QLineEdit(frame_4);
        SizeOfStackReserve->setObjectName(QStringLiteral("SizeOfStackReserve"));
        SizeOfStackReserve->setGeometry(QRect(340, 220, 101, 20));
        SizeOfStackReserve->setReadOnly(true);
        label_51 = new QLabel(frame_4);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(210, 240, 99, 20));
        SizeOfStackCommit = new QLineEdit(frame_4);
        SizeOfStackCommit->setObjectName(QStringLiteral("SizeOfStackCommit"));
        SizeOfStackCommit->setGeometry(QRect(340, 240, 101, 20));
        SizeOfStackCommit->setReadOnly(true);
        label_52 = new QLabel(frame_4);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(210, 260, 103, 20));
        SizeOfHeapReserve = new QLineEdit(frame_4);
        SizeOfHeapReserve->setObjectName(QStringLiteral("SizeOfHeapReserve"));
        SizeOfHeapReserve->setGeometry(QRect(340, 260, 101, 20));
        SizeOfHeapReserve->setReadOnly(true);
        label_55 = new QLabel(frame_4);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(210, 300, 121, 20));
        NumberOfRvaAndSizes = new QLineEdit(frame_4);
        NumberOfRvaAndSizes->setObjectName(QStringLiteral("NumberOfRvaAndSizes"));
        NumberOfRvaAndSizes->setGeometry(QRect(340, 300, 101, 20));
        NumberOfRvaAndSizes->setReadOnly(true);
        label_53 = new QLabel(frame_4);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(210, 280, 98, 20));
        SizeOfHeapCommit = new QLineEdit(frame_4);
        SizeOfHeapCommit->setObjectName(QStringLiteral("SizeOfHeapCommit"));
        SizeOfHeapCommit->setGeometry(QRect(340, 280, 101, 20));
        SizeOfHeapCommit->setReadOnly(true);
        label_54 = new QLabel(frame_4);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(210, 320, 61, 20));
        LoaderFlags = new QLineEdit(frame_4);
        LoaderFlags->setObjectName(QStringLiteral("LoaderFlags"));
        LoaderFlags->setGeometry(QRect(340, 320, 101, 20));
        LoaderFlags->setReadOnly(true);
        label_48 = new QLabel(frame_4);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(10, 290, 52, 20));
        Subsystem = new QLineEdit(frame_4);
        Subsystem->setObjectName(QStringLiteral("Subsystem"));
        Subsystem->setGeometry(QRect(70, 290, 51, 20));
        Subsystem->setReadOnly(true);
        Subsystem_Word = new QLineEdit(frame_4);
        Subsystem_Word->setObjectName(QStringLiteral("Subsystem_Word"));
        Subsystem_Word->setGeometry(QRect(120, 290, 81, 20));
        Subsystem_Word->setReadOnly(true);
        label_49 = new QLabel(frame_4);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(10, 310, 45, 20));
        DllCharacteristics = new QLineEdit(frame_4);
        DllCharacteristics->setObjectName(QStringLiteral("DllCharacteristics"));
        DllCharacteristics->setGeometry(QRect(90, 310, 51, 20));
        DllCharacteristics->setReadOnly(true);
        DLLCharacteristicsPushButton = new QPushButton(frame_4);
        DLLCharacteristicsPushButton->setObjectName(QStringLiteral("DLLCharacteristicsPushButton"));
        DLLCharacteristicsPushButton->setGeometry(QRect(150, 310, 21, 21));
        DataDirectoryPushButton = new QPushButton(frame);
        DataDirectoryPushButton->setObjectName(QStringLiteral("DataDirectoryPushButton"));
        DataDirectoryPushButton->setGeometry(QRect(10, 420, 211, 23));
        DataDirectoryPushButton->setFont(font3);
        SectionsPushButton = new QPushButton(frame);
        SectionsPushButton->setObjectName(QStringLiteral("SectionsPushButton"));
        SectionsPushButton->setGeometry(QRect(10, 450, 211, 23));
        SectionsPushButton->setFont(font3);
        ClosePushButton = new QPushButton(frame);
        ClosePushButton->setObjectName(QStringLiteral("ClosePushButton"));
        ClosePushButton->setGeometry(QRect(10, 480, 211, 23));
        ClosePushButton->setFont(font3);
        QtGuiPEClass->setCentralWidget(centralWidget);

        retranslateUi(QtGuiPEClass);

        OpenFilePushButton->setDefault(false);


        QMetaObject::connectSlotsByName(QtGuiPEClass);
    } // setupUi

    void retranslateUi(QMainWindow *QtGuiPEClass)
    {
        QtGuiPEClass->setWindowTitle(QApplication::translate("QtGuiPEClass", "QtGuiPE", Q_NULLPTR));
        msdos_label->setText(QApplication::translate("QtGuiPEClass", "MS-DOS 2.0 HEADER", Q_NULLPTR));
        e_lfanew->setText(QString());
        e_crlc->setText(QString());
        label_5->setText(QApplication::translate("QtGuiPEClass", "Memory MAX", Q_NULLPTR));
        e_lfarlc->setText(QString());
        e_csum->setText(QString());
        e_oemid->setText(QString());
        label_6->setText(QApplication::translate("QtGuiPEClass", "Overlay number", Q_NULLPTR));
        e_maxalloc->setText(QString());
        label_8->setText(QApplication::translate("QtGuiPEClass", "SP Value", Q_NULLPTR));
        e_minalloc->setText(QString());
        e_cparhdr->setText(QString());
        label_3->setText(QApplication::translate("QtGuiPEClass", "Pages in file", Q_NULLPTR));
        e_cp->setText(QString());
        e_magic->setText(QString());
        e_cs->setText(QString());
        label_14->setText(QApplication::translate("QtGuiPEClass", "Table offset", Q_NULLPTR));
        label_15->setText(QApplication::translate("QtGuiPEClass", "CS Value", Q_NULLPTR));
        label_17->setText(QApplication::translate("QtGuiPEClass", "Checksum", Q_NULLPTR));
        e_cblp->setText(QString());
        label_11->setText(QApplication::translate("QtGuiPEClass", "OEM Ident", Q_NULLPTR));
        label->setText(QApplication::translate("QtGuiPEClass", "Magic", Q_NULLPTR));
        label_10->setText(QApplication::translate("QtGuiPEClass", "Memory MIN", Q_NULLPTR));
        label_4->setText(QApplication::translate("QtGuiPEClass", "Relocations", Q_NULLPTR));
        e_ss->setText(QString());
        e_oeminfo->setText(QString());
        label_18->setText(QApplication::translate("QtGuiPEClass", "PE Offset", Q_NULLPTR));
        label_13->setText(QApplication::translate("QtGuiPEClass", "Size of header", Q_NULLPTR));
        e_ovno->setText(QString());
        label_16->setText(QApplication::translate("QtGuiPEClass", "IP Value", Q_NULLPTR));
        label_12->setText(QApplication::translate("QtGuiPEClass", "OEM Info", Q_NULLPTR));
        e_ip->setText(QString());
        label_7->setText(QApplication::translate("QtGuiPEClass", "SS Value", Q_NULLPTR));
        e_sp->setText(QString());
        label_2->setText(QApplication::translate("QtGuiPEClass", "Bytes on last pages", Q_NULLPTR));
        OpenFilePushButton->setText(QApplication::translate("QtGuiPEClass", "OPEN FILE", Q_NULLPTR));
        fileheader_label->setText(QApplication::translate("QtGuiPEClass", "FILE HEADER", Q_NULLPTR));
        label_21->setText(QApplication::translate("QtGuiPEClass", "Time/Date Stamp", Q_NULLPTR));
        label_19->setText(QApplication::translate("QtGuiPEClass", "Machine", Q_NULLPTR));
        label_20->setText(QApplication::translate("QtGuiPEClass", "Number of Sections", Q_NULLPTR));
        label_22->setText(QApplication::translate("QtGuiPEClass", "COFF Pointer", Q_NULLPTR));
        label_23->setText(QApplication::translate("QtGuiPEClass", "COFF Size", Q_NULLPTR));
        label_24->setText(QApplication::translate("QtGuiPEClass", "Size of Optional header", Q_NULLPTR));
        label_25->setText(QApplication::translate("QtGuiPEClass", "Characteristics", Q_NULLPTR));
        CharacteristicsPushButton->setText(QApplication::translate("QtGuiPEClass", "...", Q_NULLPTR));
        TimeDateStamp_dateTimeEdit->setDisplayFormat(QApplication::translate("QtGuiPEClass", "dd.MM.yyyy H:mm:ss", Q_NULLPTR));
        label_9->setText(QApplication::translate("QtGuiPEClass", "OPTIONAL HEADER", Q_NULLPTR));
        label_26->setText(QApplication::translate("QtGuiPEClass", "Magic", Q_NULLPTR));
        label_27->setText(QApplication::translate("QtGuiPEClass", "Major Linker Version", Q_NULLPTR));
        label_28->setText(QApplication::translate("QtGuiPEClass", "Minor Linker Version", Q_NULLPTR));
        label_29->setText(QApplication::translate("QtGuiPEClass", "Size of Code", Q_NULLPTR));
        label_30->setText(QApplication::translate("QtGuiPEClass", "Size of Init Data", Q_NULLPTR));
        label_31->setText(QApplication::translate("QtGuiPEClass", "Size of UnInit Data", Q_NULLPTR));
        label_32->setText(QApplication::translate("QtGuiPEClass", "Entry Point", Q_NULLPTR));
        label_33->setText(QApplication::translate("QtGuiPEClass", "Base of Code", Q_NULLPTR));
        label_34->setText(QApplication::translate("QtGuiPEClass", "Base of Data", Q_NULLPTR));
        label_35->setText(QApplication::translate("QtGuiPEClass", "Image Base", Q_NULLPTR));
        label_36->setText(QApplication::translate("QtGuiPEClass", "Section Alignment", Q_NULLPTR));
        label_37->setText(QApplication::translate("QtGuiPEClass", "File Alignment", Q_NULLPTR));
        label_42->setText(QApplication::translate("QtGuiPEClass", "Major Sybsystem Version", Q_NULLPTR));
        label_39->setText(QApplication::translate("QtGuiPEClass", "Minor OS Version", Q_NULLPTR));
        label_40->setText(QApplication::translate("QtGuiPEClass", "Major Image Version", Q_NULLPTR));
        label_41->setText(QApplication::translate("QtGuiPEClass", "Minor Image Version", Q_NULLPTR));
        label_43->setText(QApplication::translate("QtGuiPEClass", "Minor Sybsystem Version", Q_NULLPTR));
        label_38->setText(QApplication::translate("QtGuiPEClass", "Major OS Version", Q_NULLPTR));
        label_44->setText(QApplication::translate("QtGuiPEClass", "Win32 Version", Q_NULLPTR));
        label_45->setText(QApplication::translate("QtGuiPEClass", "Size of Image", Q_NULLPTR));
        label_46->setText(QApplication::translate("QtGuiPEClass", "Size of Headers", Q_NULLPTR));
        label_47->setText(QApplication::translate("QtGuiPEClass", "Checksum", Q_NULLPTR));
        label_50->setText(QApplication::translate("QtGuiPEClass", "Size of Stack Reserve", Q_NULLPTR));
        label_51->setText(QApplication::translate("QtGuiPEClass", "Size of Stack Commit", Q_NULLPTR));
        label_52->setText(QApplication::translate("QtGuiPEClass", "Size of Heap Reserve", Q_NULLPTR));
        label_55->setText(QApplication::translate("QtGuiPEClass", "Number of RVA and Sizes", Q_NULLPTR));
        label_53->setText(QApplication::translate("QtGuiPEClass", "Size of Heap Commit", Q_NULLPTR));
        label_54->setText(QApplication::translate("QtGuiPEClass", "Loader Flags", Q_NULLPTR));
        label_48->setText(QApplication::translate("QtGuiPEClass", "Sybsystem", Q_NULLPTR));
        label_49->setText(QApplication::translate("QtGuiPEClass", "DLL Flags", Q_NULLPTR));
        DLLCharacteristicsPushButton->setText(QApplication::translate("QtGuiPEClass", "...", Q_NULLPTR));
        DataDirectoryPushButton->setText(QApplication::translate("QtGuiPEClass", "DATA DIRECTORY", Q_NULLPTR));
        SectionsPushButton->setText(QApplication::translate("QtGuiPEClass", "SECTIONS", Q_NULLPTR));
        ClosePushButton->setText(QApplication::translate("QtGuiPEClass", "CLOSE", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class QtGuiPEClass: public Ui_QtGuiPEClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_QTGUIPE_H
